### ISSUE TITLE
Storybook: center examples

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1018]
Would be nice to dynamically center our storybook examples on the canvas.

This plugin might help:

https://github.com/storybookjs/storybook/tree/master/addons/centered

Then we wouldn't see overlays disappearing off the top of the screen like this (notice the infotip overlay):

<img width="786" alt="Screen Shot 2020-01-13 at 8 07 21 PM" src="https://user-images.githubusercontent.com/38065/72313528-7bbcd080-3640-11ea-898c-850570eace30.png">

**Comment by ianmcburnie** [comment]
This is low priority, but perhaps @DylanPiercey could take a quick look and see what it would take to add Marko support for this addon:

https://github.com/storybookjs/storybook/blob/master/ADDONS_SUPPORT.md

**Comment by mlrawlings** [comment]
While I'm not opposed to centering the examples, I see this as a limitation of the component itself.  The tooltip should open where there is available space.

It could argued that the `pointer` attribute should be used, but there are going to be cases where it's not possible to hard-code the optimal position due to differing screen sizes or the current scroll position.

**Comment by ianmcburnie** [comment]
@mlrawlings Yep, I agree, and we have a ticket already for that: https://github.com/eBay/ebayui-core/issues/535

**Comment by ianmcburnie** [comment]
Maybe another one for @biaspro to investigate as part of the other storybook work...

**Comment by ianmcburnie** [comment]
Done in 7.1.0.
