### ISSUE TITLE
Lasso-page should fallback to DS6

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1030]
As discussed in standup (I didn't completely follow the conversation, sorry): lasso-page should fall back to DS6 to prevent error

**Comment by ianmcburnie** [comment]
Closing... as I can't for the life of me remember what this is for...

**Comment by agliga** [comment]
Reopening, I remember what this is:

In icons we require lasso page in order to icons. However if the parent page does not have lasso page defined, it causes an error which doesn't load the page. 
We should change it so it just defaults to DS6 if it cannot load from lasso page
This line needs to be fixed because this throws an error since config is undefined (but doesn't check for config) https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-icon/index.marko#L38

**Comment by ianmcburnie** [comment]
Thanks Andrew!

**Comment by ianmcburnie** [comment]
See if this can be done in 5.6.0. Happy to wait till v6 if not.
