### ISSUE TITLE
Add Readme File to ebay-dialog-base

### ISSUE THREAD

**Issue by montoya332** [eBay/ebayui-core#1137]
Feature Request
Add Readme File to ebay-dialog-base
https://github.com/eBay/ebayui-core/tree/master/src/components/components/ebay-dialog-base
## Description
As a developer I would like to see all available attributes and events that ebay-dialog-base handles.

**Comment by agliga** [comment]
So technically developers and users should not be using this. This is entirely internal and should not be exposed to developers. 
The components that should be used are `dialog`, `toast`, and `drawer` which all use `dialog-base` and expose different attributes. Those attributes are passed in internally to `dialog-base` or change depending on the component. IE `toast` sets `isModal` to false because that's what it needs to work properly.
