### ISSUE TITLE
Combobox: scrollbar is not clickable on IE11

### ISSUE THREAD

**Issue by joinfelipe** [eBay/ebayui-core#1200]
# Bug Report

## Description
1.  Use Internet Explorer 11
2. Make sure the combobox has lots of options, enough to show scrollbar
2. Click on combobox
3. Enter some text so the combobox expands
4. try clicking and dragging the scrollbar
*Actual Behavior*
5. Combobox collapses
*Expected Behavior*
5. Combobox should stay expanded and user should be able to drag scrollbar, in order to scroll over the content.

## Workaround
User can still use the mouse wheel or use the down/up arrow from the keyboard to navigate. 

## Screenshots

![image](https://user-images.githubusercontent.com/69696226/90290357-97849100-de32-11ea-87bc-9d3fd419f0cc.png)

**Comment by agliga** [comment]
I am leaning towards won't fix since the user is still able to scroll up and down on IE11 using a mousewheel and keyboard. @ianmcburnie Can you verify this is fine to close.
If there is an issue it's probably with makeup-expander (and the same issue we fixed here for menu-button, https://github.com/eBay/ebayui-core/issues/1075)
