### ISSUE TITLE
ebay-dialog: Updating the full dialog with "open=true" keeps the dialog "hidden"

### ISSUE THREAD

**Issue by msendlakowski** [eBay/ebayui-core#1238]
# Bug Report

## Description
Render a `full` dialog on a small screen with `open` set to `false`.
Update the dialog by setting `open` to `true`.

The dialog won't visibly open.

This is the HTML before the open is triggered:
```
<div use-hidden-property="" class="dialog dialog--no-mask" aria-labelledby="s0-0-26-3-0-0[3]-3-11-follow-ebay-7-title" aria-modal="true" role="dialog" hidden="">
```

This is the HTML after the open is triggered.  Note that "hidden" is still applied:
```
<div use-hidden-property="" class="dialog dialog--no-mask dialog--show" aria-labelledby="s0-0-26-3-0-0[3]-3-11-follow-ebay-7-title" aria-modal="true" role="dialog" hidden="">
```

I think the problem is in this area.  The transition end event is never called:
https://github.com/eBay/ebayui-core/blob/master/src/components/components/ebay-dialog-base/component.js#L177-L181

If I put a breakpoint there and use the console to remove "hidden" before the transition occurs then the transition happens as expected and the transition end event is called.

## Workaround
None

## Screenshots
![Screen Shot 2020-09-17 at 5 19 12 PM](https://user-images.githubusercontent.com/1562843/93540921-fcd41200-f909-11ea-9839-f4a807a4b5cb.png)

**Comment by agliga** [comment]
Just to update, the issue is due to the parent app having a style of:
`[hidden] { display: none !important; }`
What we do with our dialog is we have it `display:none` when `[hidden]`, however when we apply `-show-init` it should change the display to `display: block;` (or in newer versions `display: flex;`). This then begins the animation. Once the animation starts then `-show` is applied. When completed then hidden attribute is removed `onFinishTransition`. 
One of the ways to fix this is to force the `display: flex` to be `!important` if that style conflicts with others and then it should take precedence over the `[hidden]` one. 
The problem is that the initial `display: block` is never applied since `display: none` on hidden is `!important`. This means no animation is taking place, and no trigger of `onFinishTransition`. 
We should see if that style can be changed to not be `!important`, or we can change our display ones to be `!important` in order to fix this. However, I would prefer not to have to use `!important` since it really should not be used.

**Comment by msendlakowski** [comment]
Thanks @agliga
