### ISSUE TITLE
ebay-fake-button primary color gets hidden on clicking the dropdown

### ISSUE THREAD

**Issue by deenabay** [eBay/ebayui-core#1253]
# Bug Report

## eBayUI Version:
    "@ebay/ebayui-core": "^6.0.0-4",
    "@ebay/skin": "^11.0.0-4",

## Description
ebay-fake-button primary : the black text on the button is not readable after clicking on it.
CC: @agliga 

## Workaround
The button text might needs to be shown in a different color on clicking.

## Screenshots
![image](https://user-images.githubusercontent.com/71992704/96634176-fc46e680-12ce-11eb-9931-0b3baf8d82eb.png)

**Comment by agliga** [comment]
This is due to skin missing the styles for `color` on `:hover` for primary button.
`.customColorProperty(expand-button-hover-foreground-color);` this is taking priority which is the same color as the background on primary. 

It looks like this needs to be either copied or changed to be `customColorProperty`:
`.customBorderColorProperty(button-primary-hover-foreground-color);`
@ianmcburnie I see it's deprecated, is this being removed?
This is what it looks like when hovering:
![Uploading Screen Shot 2020-10-21 at 9.13.06 AM.png…]()
