### ISSUE TITLE
Pass originalEvent for all custom events with direct mapping to DOM event

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#126]

**Comment by yomed** [comment]
To provide a bit more context: When using DOM events in Marko, it automatically passes the native DOM event object to the handler. For eBayUI, all of our events are custom, so that object does not get passed by default. For cases like `button-click`, it directly maps to the click event, so we should pass along that object.

**Comment by senthilp** [comment]
@yomed Are you proposing this for any DOM event that we wrap with a custom event? Or only for `button-click`?

**Comment by DylanPiercey** [comment]
I think we had talked about this in a standup before (specifically around having the ability to `preventDefault` though).

I still think exposing some kind of `originalEvent` property on the custom event would be useful.

**Comment by yomed** [comment]
@senthilp I think we should go through all the events on each component, and add this in any case where there's a clear mapping to a native DOM event. 

I was trying to figure out naming -- I think `originalEvent` works.

**Comment by senthilp** [comment]
Agree, we should do it for each component which emits an event that maps to a native DOM event. `originalEvent` LGTM.

**Comment by seangates** [comment]
Agree, @yomed.

**Comment by ianmcburnie** [comment]
Agreed.

**Comment by yomed** [comment]
Fixed this for the button, now repurposing the issue for all components.
