### ISSUE TITLE
`ebay-lightbox-dialog` doesn't emit `close` event when clicking outside modal 

### ISSUE THREAD

**Issue by StefanHeng** [eBay/ebayui-core#1474]
# Bug Report
To duplicate the issue, take the default `ebay-lightbox-dialog` example, also attached below: 
```marko
<ebay-lightbox-dialog a11y-close-text="Close Dialog" open=state.open on-close('closeDialog')>
    <@header>Heading</@header>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p><a href="http://www.ebay.com">www.ebay.com</a></p>
</ebay-lightbox-dialog>
 
<ebay-button on-click('openDialog')>
    Open Dialog
</ebay-button>
 
class {
  onCreate() {
    this.state = { open: false };
  }
  openDialog() {
    this.state.open = true;
  }
  closeDialog() {
    this.state.open = false;
  }
}
```

As long as I add a `buttonPosition="hidden"` attribute to the component to the example above, the error occurs, i.e. the close event is not emitted when I click outside of the modal. 

Once the attribute is removed, the event is emitted, i.e. no problem,

**Comment by agliga** [comment]
This is intentional.

First off `buttonPosition` is an internal attribute used by our dialogs and is not fully supported by teams to use. They can be used in certain situations, but are not going to be supported. 
Second off, `hidden` button position is used by `alert-dialog` and `confirm-dialog`. In that case we need to suppress the closing of the dialog by clicking outside because the only way to close those dialogs is to click the confirm/cancel buttons. 
Here is the change with the blame which is preventing clicking outside on `hidden` `buttonPosition`: https://github.com/eBay/ebayui-core/blame/master/src/components/components/ebay-dialog-base/component.js#L46-L50
