### ISSUE TITLE
Combobox: does not expand when using control+option+space keys in VoiceOver

### ISSUE THREAD

**Issue by bhoomisatasiya** [eBay/ebayui-core#155]

**Comment by ajay2507** [comment]
@ianmcburnie Can I work on this issue?.

**Comment by yomed** [comment]
@bhoomisatasiya I tried to reproduce this issue. In Safari, the key combo seems to work fine. In Chrome, the key combo does not open the `<ebay-select>`, but it doesn't open a regular native `<select>` either. I'm closing, since browser behavior is maintained. Please let me know if you still think this is an issue.

**Comment by ianmcburnie** [comment]
I believe this ticket was created before the select/combobox split. I still see the issue for combobox, so I will update the title and re-open.

**Comment by msendlakowski** [comment]
I see this behaving as expected, if I understand the issue correctly.
http://app.uimarketplace.svc.32.tess.io/?tag=ebay-combobox#examples

I'm closing the ticket, but I've reached out to @bhoomisatasiya to confirm when she's back at work.
