### ISSUE TITLE
Focus is lost when a ebay-menu-button item open a dialog

### ISSUE THREAD

**Issue by cc-ebay** [eBay/ebayui-core#1612]
# Bug Report

## Description
I have a problem with focus on a `ebay-menu-button` - One of the item `on-select` opens a dialog.
When the dialog closes, the focus is on a element at the bottom of the page instead of the `ebay-menu-button`.

## Workaround
As a work around I added `el.closest('.menu-button').querySelector('.menu-button__button').focus();`  in the `select` event but  the component should do something about it.

**Comment by agliga** [comment]
So technically there isn't anything we can do about this
The reason is becasue when you click an item on `menu-button` that element you click on will become the focus element, not the menu-button items. When the dialog closes, it will try to focus that element but because it is hidden it will not. 
One possible solution is to have an argument like we have `focusEl` to have `closeFocusEl`, which is the element which the dialog will focus when it's closed. 
@ianmcburnie any thoughts?

**Comment by ianmcburnie** [comment]
I agree with `closeFocusEl`

**Comment by cc-ebay** [comment]
Are you saying to add `closeFocusEl` as an attribute of the dialog? 
Did you think how the code will look like if you do this? 
Would not be make more sense to have that attribute in the `.open` function of the dialog?

**Comment by agliga** [comment]
> Are you saying to add `closeFocusEl` as an attribute of the dialog? Did you think how the code will look like if you do this? Would not be make more sense to have that attribute in the `.open` function of the dialog?

Similarly to how we have `focus` attribute on dialog to force the initial focus element, we can add `closeFocusEl` which you can pass the menu-button selector. When the dialog closes it will focus that.
