### ISSUE TITLE
ebay-listbox-button: add collapseOnSelect attribute

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1636]
Add `collapseOnSelect` option to listbox-button so that listbox can auto collapse after selection is made (we did something similar for menu button)

**Comment by agliga** [comment]
We already collapse on select on listbox selection. This change would make it so we don't collapse on select on click.
The issue is we have two collapse types: On click we collapse, when we select with keyboard we do not collapse. 
So we can either: leave as is, fix to keep it open for click, or force both based on this attribute.

**Comment by agliga** [comment]
FYI, the logic was added in this ancient issue: https://github.com/eBay/ebayui-core/pull/805

**Comment by agliga** [comment]
We will also need to manage focus, by removing that event collapse it loses focus (need to focus back to button)

**Comment by ianmcburnie** [comment]
Thanks. You are correct, it already does this. It must have been an issue on the app side that I saw. Going to close this.

**Comment by PrashantAshok** [comment]
@ianmcburnie - This is reproducible in storybook as well https://ebay.github.io/ebayui-core/?path=/story/ebay-listbox-button--standard 

selecting an option via keyboard, does not auto collapse the dropdown.

**Comment by ianmcburnie** [comment]
Interesting. The behavior for kb and mouse should match. Reopening.
