### ISSUE TITLE
ebay-carousel: existing tabindex value is being clobbered

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#1762]
# Bug Report

## Description

The ebay-carousel adds `tabindex=-1` to any interactive element that moves outside of the viewport (to prevent kb access to it).The `tabindex` attribute is then removed when the item comes into view.  The issue is that this brute-force removal is too aggressive, and any _pre-existing_ tabindex is not restored back to its initial state.

To summarize: if an element was rendered with ` tabindex=-1`, our code is not restoring that value when it comes back into view.

The same issue applies to `aria-hidden`.

https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-carousel/component.js#L93-L103

An example of this behavior can be found here on the refurbished items carousel: https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw=iphone&_sacat=0#mainContent

## Workaround

None

## Dev Notes

![Screen Shot 2022-09-19 at 12 34 25 PM](https://user-images.githubusercontent.com/38065/191100719-30c59cdc-a095-4688-807c-f687e6d03e6e.png)

**Comment by agliga** [comment]
The problem is we don't know what the initial tabindex is. This is run on render. We could do a check if it's first render to preserve the tabindexes, but if they change from the parent, then we have no idea if it was first render, or if we are rerendering. If we do the first render, then it should be pretty easy to remember the tabindex. But if any of the structure changes, we could lose that or cause mismatches. 
There are several possible ways to get around this. We could ask teams to have something like a `data-tabindex` on each item they want to be restored, so we know what the initial value is. Or we can add that `data-tabindex` and say it only works on initial render and then restore it as needed.

**Comment by agliga** [comment]
Based on my discussions with Dylan, we will add support for users to pass a `default-tabIndex`, which if set we will default to when we remove the tabindex. The users can add this to any element inside the carousel and we will look for it when we reset the tabindex, otherwise we will remove the tabindex.
