### ISSUE TITLE
Radio: FPS issue

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#201]
## Description
when I select a radio option I see a peak.
fps comes down to 12-25

reproducible in both marketplace and test page

https://go/ebayui/market
https://go/ebayui/test2
most of the time is consumed in scripting.
## Screenshots

![image](https://user-images.githubusercontent.com/13157115/40517936-cacf6a2c-5f6c-11e8-88bb-5c035d4faf46.png)

**Comment by hramakumar** [comment]
will attach the profile

**Comment by hramakumar** [comment]
[Profile-radio.zip](https://github.com/eBay/ebayui-core/files/2037441/Profile-radio.zip)

**Comment by PrashantAshok** [comment]
Had a look at this in the marketplace/test page. The scripting time is actually less than 4~5ms. The fps is normal too. The widget is also not performing any animations or complicated scripting. 

@DylanPiercey, feel free to pitch in case I missed anything. 

<img width="584" alt="screen shot 2018-06-07 at 1 38 18 pm" src="https://user-images.githubusercontent.com/5200733/41131589-431416ae-6a71-11e8-9630-5afcf3231cd5.png">

**Comment by DylanPiercey** [comment]
We have already discussed this one and it can be closed 🙂. Happens because the browser paints the focus ring when you click and we update the dom after release of the click. This causes two frames of arbitrary spacing with potentially no intermediary frames. As @PrashantAshok mentioned the scripts here aren’t causing any sort of bottle neck.

**Comment by ianmcburnie** [comment]
Thanks for the detail @DylanPiercey and @PrashantAshok. Closing.
