### ISSUE TITLE
Combobox: when text is long it gets displayed over the component down arrow at the right

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#224]
# Bug Report

## Description
 when text is long it gets displayed over the component down arrow at the right
https://www.useloom.com/share/d6894758310e4a8fbddf3838f296a051

**Comment by ianmcburnie** [comment]
This may need fixing on the skin side.

**Comment by msendlakowski** [comment]
Moving this back to the backlog since we are not recommending that the combobox be used until the typeahead functionality is there.
To see the fix see this commit:
https://github.com/eBay/skin/pull/330/commits/754c031b30f86a866f6fcc8396895193ba1d0dc2

But there was a weird display issue on focus/blur of the input.  See this comment:
https://github.com/eBay/skin/pull/330#issuecomment-414919920

**Comment by seangates** [comment]
@msendlakowski Since this is done in Skin, is there anything still to be done in eBayUI?

**Comment by msendlakowski** [comment]
@seangates I'll verify when the next build is out and close it.

**Comment by hramakumar** [comment]
it is fixed
![image](https://user-images.githubusercontent.com/13157115/46306005-de7f7b00-c567-11e8-9370-6413d68e2627.png)
