### ISSUE TITLE
ebay-select: the down arrow on the right  does not switch to up arrow when the ebay select component is expanded

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#226]
# Bug Report

## Description
the down arrow icon on the right does not switch to up arrow when the ebay-select component is expanded

repro: go to https://go/ebayui/test
click on any of the ebay-select components in the test page
the expand arrow does not change to ^ arrow mark

https://www.useloom.com/share/3a72b363ba784bda9743981b04345695

## Screenshots

![image](https://user-images.githubusercontent.com/13157115/42013753-9d5d3478-7a53-11e8-9d46-892285a8b0b1.png)

**Comment by seangates** [comment]
Which browser/OS? Mac browsers (Chrome, Safari, Firefox) cover up the chevron, but it appears Windows is different?

**Comment by hramakumar** [comment]
this happens Windows desktop and Android tablet - all browsers

**Comment by seangates** [comment]
Which version of Windows? It doesn't happen for me with IE11 on Windows 8.1.

![image](https://user-images.githubusercontent.com/105656/42014253-87488e16-7a5e-11e8-8111-2e7118698e13.png)

**Comment by hramakumar** [comment]
mine is windows 7

**Comment by hramakumar** [comment]
actually yes in ie it doesn't happen. check chrome and firefox you should be able to reproduce

**Comment by seangates** [comment]
After some research this evening, I can't find any way to detect that a select menu is open, whether through CSS, JavaScript, or otherwise. I even tried to change the chevron to an inline SVG, but that won't work either, because I simply never know when the `<select>` is actually open (or closed, for that matter).

Therefore, I'm going to close this as there is no solution. We'll simply have to live with it still showing a chevron pointing down.

@ianmcburnie Let me know if you feel otherwise and we can reopen the issue.

**Comment by seangates** [comment]
Also, I should note, that this is expected browser behavior, so we don't have any way to solve this other than to tell teams to use the `ebay-combobox`.
