### ISSUE TITLE
Carousel: Async/Lazy items for next page

### ISSUE THREAD

**Issue by sraone** [eBay/ebayui-core#361]
# Feature Request
Carousel should allow loading the next page items from Ajax call as user navigating to next/prev pages.

**Comment by msendlakowski** [comment]
Thanks.  Its a good suggestion.

I think what we would probably do is allow you to update your items and rerender the carousel.  You would have to listen for the 'next/previous' events and manage the ajax request on your own.  (You would probably want to do that at least one page ahead of the current slide.)

@DylanPiercey   If they need this now, can they update the items and then call `setStateDirty('items')`?  At least in Marko v4?  



you need this now I think you could listen for the next and previous events and make your requests at that time.  Then you could update your items and then call setState(

**Comment by DylanPiercey** [comment]
@msendlakowski this is possible now. If you re-render the carousel with new items it will update accordingly.

Something that may be required to support this is to allow the default navigations to be postponed and to show a loading state while we are waiting for the Ajax call to be appended. Ultimately all of this should be able to take place (and should take place) on the users side.

I'd also say that this would be a bad user experience and that you should at least have a few slides available for the user the navigate through and maybe you can lazily load the rest which is currently possible just by rerendering your component which uses the carousel.

**Comment by sraone** [comment]
@msendlakowski @DylanPiercey thanks for quick response. The issue is when I manually update the state `items` array(inserting or removing), it's re-render the carousel and the user lose his current state.

For example, if user navigated to second slide and state is updated with next slide items, the re-render would take the user back to first page. It would be bad experience for user or blocker.

**Comment by DylanPiercey** [comment]
@sraone gotcha. The way I would normally recommend doing this would be to sync your components state with the carousel state (index in this case) so that when you rerender your items the selected index from the user is persisted.

In this case what you would want to do in this case is listen for the `carousel-update` event and update the state of your component to keep track of the index so that when you re-render the items the index stays the same like so:

```marko
class {
  onCreate() {
    this.state = {
      carouselIndex: 0
    }
  },
  
  handleUpdate(details) {
    this.state.carouselIndex = details.index;
  }
}

<div>
  ...

  <ebay-carousel index=state.carouselIndex on-carousel-update('handleCarouselUpdate')>
    ...
  </ebay-carousel>
</div>
```

Currently we do not emit the index on `carousel-update` only the visible indexes which is not the most helpful and so you could change `handleCarouselUpdate` to:

```js
  handleUpdate(details) {
    this.state.carouselIndex = details.visibleIndexes[0];
  }
```

I think it would be worthwhile to emit the selected index on changes as well though.

**Comment by sraone** [comment]
@DylanPiercey Thanks again for a quick workaround. But I could see a flicker for a moment. Is there a way to avoid the flicker?

**Comment by DylanPiercey** [comment]
@sraone are you able to put up a gif or something of what you are seeing? My guess is that it's flickering because you are actually fetching the data from the server as soon as they click next but the carousel starts moving before the response happens. This is what I was referring to when I mentioned that to support this we would need to have a way for you to prevent the `prev/next` buttons to wait for your Ajax call to finish before updating. I feel like that this is not a good idea though.

How many items are in your carousel? Why are we using Ajax to load carousel items anyways? Like I said Ideally you would do something like preloading the previous 2 slides and the next 2 slides whenever the index changes to prevent a hang when the user clicks the buttons.

**Comment by sraone** [comment]
> How many items are in your carousel? Why are we using Ajax to load carousel items anyways? Like I said Ideally you would do something like preloading the previous 2 slides and the next 2 slides whenever the index changes to prevent a hang when the user clicks the buttons.

@DylanPiercey Yes, I am already preloading items for 2 slides on initial load. When the user is navigated to next page, again I am preloading items for next 2 slides. But changing the state manually, that re-rendering entire carousel and causing this issue.

**Comment by sraone** [comment]
Hi, Is there any plan to fix this issue?

**Comment by ianmcburnie** [comment]
Assigning to @DylanPiercey to follow up and see if this is still an issue and worth fixing for MarkoV3, or punting till we move to MarkoV4. Given that there hasn't been much ask for this, I feel like we can probably punt it, but if it's quick to diagnose and an easy fix we might aswell do it now.

**Comment by ianmcburnie** [comment]
We decided to punt this till after v4.0.0. Dylan feel free to jot down any notes in here that might be useful while it's fresh in your head.

**Comment by msendlakowski** [comment]
Addressing when we move to Marko v4

**Comment by ianmcburnie** [comment]
Punting this to v6 as part of #963

**Comment by agliga** [comment]
This should be able to be working now, teams are doing this.
