### ISSUE TITLE
Discussion: Conflicting ways to update component states

### ISSUE THREAD

**Issue by msendlakowski** [eBay/ebayui-core#376]
From Chris Cinelli on the Slack channel:

Why on dialog (other components seem to follow the same pattern) you have 3 different ways to close and open the dialog:

1.  `open` prop in the "HTML"
2.  `show()/close()`
3.  `observer.observeRoot(this, ['open']);` for addressing `dialog.open = true`

The `open` prop with an external state seemed sufficient.
The problem is not having multiple ways to do the same thing but the confusion among `open` prop and the `open` state.
If you want to keep the state internally, should not the prop be something like `initialOpenState` to clarify that it can mutate?

I think it should be clear where the `open` state is.

Let says I have :
```<other-component aprop=anotherState> 
  <ebayui-dialog open=isTheDialogOpen> 
    ...
  </ebayui-dialog>
</other-component>``` 

Let says `isTheDialogOpen` is `false`. Dialog open in some way... then I use in one place `close()` and then the `isTheDialogOpen` outside of the dialog switch to `true`... what happens? What if `anotherState` changes?  It seems the result may surprise who is using the component.

**Comment by yomed** [comment]
I agree that it's confusing. I think that setting state declaratively through Marko is sufficient, and that we don't need the methods or DOM observers.

**Comment by seangates** [comment]
Also, keeping observers and methods just means we open things up to abuse by developers who manipulate an element's state, usually without them having a knowledge of how proper Marko state management should be done.

And it will simplify our code, which is also less code sent to the browser.

**Comment by ianmcburnie** [comment]
Answer: because this follows the same paradigm as HTML and the DOM. We are striving to be HTML-like, rather than Marko-like, so that any future migration to web-components/custom-elements will be more seamless:

https://medium.com/@senthil_hi/building-a-ui-component-in-2017-and-beyond-1f6d5c4d464

The `open` prop is entirely sufficient *if* you come from a stateful Marko world, and subscribe to that world as the only way of doing things. But yes, there is a valid argument that this is a Marko framework and the components should be doing things the Marko way, not the HTML way. 

I do agree that some better naming of properties could help clear up people's confusion.

**Comment by ianmcburnie** [comment]
@senthilp Care to comment on this? Marko state management vs being HTML/DOM-like.

**Comment by senthilp** [comment]
I am talking with a couple of FE folks next week. Will update back once I hear the feedback.

**Comment by ianmcburnie** [comment]
@senthilp How was the feedback? This topic could crop up again in the brownbag.

**Comment by senthilp** [comment]
I hear both ways. Folks were OK if this is only for core components. For app components, we should leverage the Marko model. I would suggest that we leave core as such. We can discuss more in our standup.

**Comment by ianmcburnie** [comment]
Thanks Senthil!

**Comment by seangates** [comment]
That sounds appropriate, and follows my thinking.
