### ISSUE TITLE
Dialog: changing stateful "open" property via direct DOM manipulation does not work

### ISSUE THREAD

**Issue by ccinelli** [eBay/ebayui-core#583]
# Bug Report

## Description
```
class {
    onCreate(input) {
        this.state = {
            selectedDate: false,
        };
    }

    open(opt) {
        this.state.selectedDate = new Date();
        this.el.querySelector('.side-dialog').open = true; // Workaround: put this in a setTimeout (..., 10)
    }
};

<lasso-page flags="ebayui-no-bg-icons"/>

<div>
    <span>Date: ${state.selectedDate}</span>
    <div>
        <ebay-button class="open" priority="primary" on-button-click('open')>Open</ebay-button>
    </div>
    <ebay-dialog class='side-dialog' type="right" a11y-close-text="Close Dialog" aria-labelledby="dialog-title" open=state.dialogOpen>
        <p>Just a dialog</p>
    </ebay-dialog>
</div>
```

Clicking "Open" button the dialog does not open.

## Workaround
See comment

**Comment by ianmcburnie** [comment]
@DylanPiercey if changing the DOM attribute directly, as Chris is doing above, is it expected that a timeout would be needed? I know we aren't supposed to be mixing Marko approach with imperative approach, but I wonder if the same issue exists if trying to change the attribute in a non-Marko button click handler...?

**Comment by senthilp** [comment]
A timeout should not be needed. Not sure why it is not working directly.

**Comment by DylanPiercey** [comment]
The issue here is that you should use the Marko api when consuming these components with Marko instead of the imperative element reference API. I've mentioned many flaws with exposing this alternative API which I'll highlight again:

1. Potential for conflicting with existing or future DOM api's
2. Increased API surface leads to confusion (like this) where Marko consumers should use the Marko api.
3. More complicated code base and documentation to support both API's.

At the very least we need to document this better. The reason @ccinelli went down this path and tried using this API was because of the confusion around updating the stateful open attribute as discussed in [this issue](https://github.com/eBay/ebayui-core/issues/582).

Also here is a discussion we've had previously on the topic where I did not chime in https://github.com/eBay/ebayui-core/issues/376

**Comment by ianmcburnie** [comment]
Totally agree that Marko API should always be used where possible. But without the imperative element reference API, how would non-marko code on the page open or close the dialog? Or collapse a menu, or listen to raw DOM events? I know it seems like a bit of an edge case that this might happen (aren't we all supposed to be using Marko after all?) but this was one of the features we highlighted way back in first demo (opening the inspector and changing a stateful property).

I agree that the documentation is the biggest issue here (issue 2 above). We can maybe all put our heads together and think of a way to keep the API docs clearly distinguished and/or separated.

We could at some point in time reach a conclusion that we shouldn't support this extra API, but for now (and to make progress on this specific ticket) we need to verify that `querySelector('.dialog').open = true` works when called outside of Marko.

1) is interesting and I kind of alluded to it yesterday, where it's becoming a bit confusing which attributes in the Marko template belong to Marko, CoreUI or HTML. Anyhow, I don't want to get into that in here...  :-)

**Comment by ianmcburnie** [comment]
Can close this old ticket. We have long since dropped the imperative API.
