### ISSUE TITLE
Infotip: breaks when nested inside paragraph of text

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/ebayui-core#729]
I tried adding the infotip inside the first paragraph of text inside the marko starter app:

```html
<p>
We're glad you've decided to try out Marko. 
<ebay-infotip a11y-close-text="Dismiss infotip" aria-label="Important information">
  <ebay-infotip-heading>Important</ebay-infotip-heading>
  <ebay-infotip-content><p>This is some important info</p></ebay-infotip-content>
</ebay-infotip>
You're looking at the result of <code>~/src/index.marko</code>. Try editing that file and this page will reload. &#9889;
</p>
```

It gobbled up the text preceding it, and failed to show its own content:

![Screen Shot 2019-07-01 at 9 55 30 AM](https://user-images.githubusercontent.com/38065/60453606-6cb38b00-9be6-11e9-81a7-74148692d570.png)

**Comment by agliga** [comment]
This is due to the fact that a DIV in HTML closes the <p> tag. 
https://stackoverflow.com/a/34683474
The <div> for the overlay is closing the <p> tag and generating it outside the <p> tag. When a lookup  to fetch the nested overlay occurs, it fails because there is no nested overlay. 
Need to change the <div> for overlay to a span in order to fix this.

**Comment by ianmcburnie** [comment]
Ok. There are several DIV tags being used in infotip, and I just tried changing the `infotip__mask` to a span and it breaks things, so we might have to do this in skin v8.0.0 & v3.0.0

```html
<span class="infotip">
    <button class="icon-btn infotip__host" type="button" aria-expanded="false" aria-label="Help">
        <svg aria-hidden="true" class="svg-icon" focusable="false" width="16" height="16">
            <use xlink:href="#icon-information"></use>
        </svg>
    </button>
    <div class="infotip__overlay">
        <span class="infotip__pointer infotip__pointer--top-left"></span>
        <div class="infotip__mask">
            <div class="infotip__cell">
                <span class="infotip__content">
                    <h3 class="infotip__heading">Infotip</h3>
                    <p>Here's a tip to help you be successful at your task.</p>
                </span>
                <button aria-label="Dismiss infotip" class="infotip__close" type="button">
                    <span aria-hidden="true" role="img"></span>
                </button>
            </div>
        </div>
    </div>
</span>
```

**Comment by ianmcburnie** [comment]
In the meantime there is a workaround for this, use a `div` tag instead of a `p` tag, but that's not great for semantics, obviously.

**Comment by ianmcburnie** [comment]
Just thought... if we wanted to get this fix out now we could potentially change the markup in coreui and add some local css overrides. Then in v3.0.0 we could remove them.

**Comment by seangates** [comment]
That would work.

**Comment by agliga** [comment]
@ianmcburnie What would you have in mind, like instead of doing <p> have a <div> with a class of flyout paragraph or something?

**Comment by ianmcburnie** [comment]
Just change all divs to spans, one at a time, and see what breaks in terms of the skin css. Then add local overrides.

**Comment by agliga** [comment]
I think we need to rethink this.
So the header will also cause an issue because `<h2>` is not allowed inside a paragraph. 
Also if the user will include any content that has a `<div>` `<h2>` or any block tags, it will break and not render correctly. 
I think part of the fix is to make an option to render the overlay outside the paragraph tag. That way the overlay will not be restricted by its content.

**Comment by agliga** [comment]
We might think about having the tooltip content render and be mounted directly in the body of the document. That way it isn't affected by any other markup.

**Comment by ianmcburnie** [comment]
The content needs to be immediately after the button in the DOM for accessibility.

**Comment by agliga** [comment]
So realistically nesting an overlay inside `<p>` becomes very difficult if the content needs to be after the button. Because as long as there is a block element nested, it will break.

What about making the infotip focus on tabbing out of the button? Then when the user blurs out of the info tip it goes to the next element and closes the info tip? Could that work in terms of accessibility?

I change the elements for now, and it can work (although it might need some styles because it looks like the default example requires a `<p>` tag in the content which also does not work). What we need to warn users is to make sure they do not include any `<p>`, `<div>`, or any `<h2>` inside an infotip nested in a paragraph. 
Let me know what you recommend with this. I do think it is a breaking change.

**Comment by ianmcburnie** [comment]
Well, not every user presses TAB. Screen reader users for example might move their virtual cursor forward instead. Until `aria-flowto` becomes well supported, it's best just to have the DOM take care of the natural reading order. 

Another option is focus management. Keyboard focus is moved to the overlay as soon as the button is activated. This forces all users to the right place to read the tip. But getting them back to the right place, and keeping them in the right place, after they have finished is the tricky bit. Unless we use a modal. Which isn't entirely out of the realms of possibility, but I'd rather not do right now. So yeah, a can of worms! Let's just restrict users to non-block level tags for now.

**Comment by agliga** [comment]
👍 
I will add a change to support both <spans> and <p> (to keep existing functionality on non nested `<p>`). Will add an example with documentation to say not to nest
