### ISSUE TITLE
Button: hover over disabled changes color

### ISSUE THREAD

**Issue by hramakumar** [eBay/ebayui-core#777]
# Bug Report

## Description
hover over disabled button changes color grey highlighted.
expected- no change on hover
https://www.loom.com/share/5cb64fffeb9b4e479d39e2dbe3152c92

**Comment by seangates** [comment]
@hramakumar Were you able to get it to have a hover effect that after you clicked it? Or focused it? Or even without focusing or clicking you could get it to have a hover effect?

**Comment by hramakumar** [comment]
no even without focus or clicking
you the try it urself in the test page
go/ebayui/test

**Comment by agliga** [comment]
This is caused by skin, namely this PR: 
https://github.com/eBay/skin/pull/647
It seems that it was intentionally added to add styles on :hover, @seangates @ianmcburnie is this correct?

**Comment by ianmcburnie** [comment]
@agliga We definitely shouldn't have a hover style for disabled. If it's an easy fix, go for it. But we've gone back and forth on these so I'm wary of further regressions. So yeah, take a quick look and see if it's an easy one, otherwise I say we leave it until we've finished splitting up and refactoring the buttons as part of v8 and ds6.5.

**Comment by agliga** [comment]
Fixed by upgrading skin to `7.4.5`
https://github.com/eBay/ebayui-core/commit/de41afdc53a5b66dd2ca143febe27c6a29567751
