### ISSUE TITLE
Change browser.json to require widget properly

### ISSUE THREAD

**Issue by agliga** [eBay/ebayui-core#958]
# Bug Report

## Description
`<ebay-filter>` wasn’t  being sent to the browser.  And it turns out our browser.json files in @ebay/ebayui-core don’t use require: .  I’m kinda at a loss of how this works at all right now with that missing…
If we change the root `ebay-filter.browser.json` from
```
{
    "dependencies": [
        "./dist/components/ebay-filter"
    ]
}
```
to
```
{
    "dependencies": [
        "require: ./dist/components/ebay-filter"
    ]
}
```
the component is loaded.

This is only for marko v3, for v4 this is not needed and will work properly.

**Comment by ianmcburnie** [comment]
@agliga Is this just for eBay-filter, or other/all components?

**Comment by agliga** [comment]
I believe it's for all components that are sent to the browser. 
The browser.json is generated by the prepublish script so the change would be to add a `require:` here https://github.com/eBay/ebayui-core/blob/master/scripts/prepublish.js#L19
However, we would need to test all these components then to make sure nothing is broken (and this is a post publish fix only)

**Comment by mlrawlings** [comment]
All components should be using `require: ` for the component/widget file in the `browser.json`.  This causes the component/widget to be included in lasso's bundle as a require-able module.  Marko 3 then uses a lasso-specific path to load this from the lasso bundle and initialize the component in the browser.  (This is the part of Marko 3 that's tied to lasso - it no longer works this way in Marko 4)

**Comment by agliga** [comment]
@mlrawlings So pagination does do `require: index.js` in it's `browser.json`. https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-pagination/browser.json#L12
So since it is there do we also need the top level require too?

**Comment by mlrawlings** [comment]
Ohhh... I think the issue is different than what I originally described:

The top-level `browser.json` files generated at [prepublish](https://github.com/eBay/ebayui-core/blob/master/scripts/prepublish.js#L19) end up loading the `browser.json` files in each of the components (there's an implicit `package: ` prefix).  This is fine.  

The actual problem is that the [`ebay-filter/browser.json`](https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-filter/browser.json) doesn't have `require: ./index.js`.

I "fixed" it by causing the top-level to require that `index.js` file, but it really should be the inner `browser.json` that has it.

I was very confused... this make so much more sense.

I'll also note that if one of these components gets included under another stateful widget, the `index.js` will get pulled in by that component, even if it's not in the `browser.json`.  This is probably why it wasn't caught earlier.

As @agliga mentioned, [ebay-pagination/browser.json](https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-pagination/browser.json#L12) has the correct `require: `.  
We should check to make sure that's the case for all these components.

**Comment by agliga** [comment]
So we simply have to add `require:index.js` in [ebay-filter/browser.json](https://github.com/eBay/ebayui-core/blob/master/src/components/ebay-filter/browser.json)

**Comment by mlrawlings** [comment]
I think so, yes.
